# Generated by Django 4.1.5 on 2023-01-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=55)),
                ('phonen_number', models.CharField(max_length=13)),
                ('DOB', models.CharField(max_length=50)),
                ('selectM_membership_plan', models.CharField(max_length=150)),
                ('select_trainer', models.CharField(max_length=55)),
                ('reference', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('paymentStatus', models.CharField(blank=True, max_length=55, null=True)),
                ('price', models.IntegerField(blank=True, max_length=55, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
