# Generated by Django 4.1.5 on 2023-01-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitnessapp', '0002_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='phonen_number',
            new_name='phone_number',
        ),
    ]
